### ISSUE TITLE
Cannot change minSDK to lower than API 21

### ISSUE THREAD

**Issue by daxthink** [GoogleCloudPlatform/abelana#5]
When I tried to change minSdkVersion to 15, I got the following error:

Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/google/common/annotations/Beta.class

**Comment by lesv** [comment]
He should have set the minimum to 16, 15 is a bit low at this point. http://developer.android.com/about/dashboards/index.html

**Comment by daxthink** [comment]
Hi Les,

Thank you so much for your help.
I have tried minSdkVersion with API 19, 18, and 15. They all compiled, but once I run it in Android Studio, it stuck with the error:
:app:collectDebugMultiDexComponents
:app:packageAllDebugClassesForMultiDex FAILED
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/google/common/annotations/Beta.class

Once I change the min back to API 21, I can run it. Any suggestion? 

Thank you again!!

**Comment by jordan-bryant** [comment]
Hi daxthink,

Have you resolved this problem,and if you have,Please help me how to resolve

Thank you!
